server:
  port: 8081
  address: 10.104.5.38
  servlet:
    context-path: /

app:
  id: sentinel-dashboard

apollo:
  meta: http://10.28.19.196:18086/
  autoUpdateInjectedSpringProperties: false
  bootstrap:
    enabled: true
    namespaces: application

project:
  name: sentinel-dashboard

spring:
  application:
    name: sentinel-dashboard
  cloud:
    sentinel:
      eager: true
      transport:
        dashboard: 'http://10.104.9.91:8085'
      datasource:
        ds1:
          apollo:
            namespaceName: application
            flowRulesKey: ${spring.application.name}-flow-rules
            ruleType: flow
        ds2:
          apollo:
            namespaceName: application
            flowRulesKey: ${spring.application.name}-degrade-rules
            ruleType: degrade
        ds3:
          apollo:
            namespaceName: application
            flowRulesKey: ${spring.application.name}-param-flow-rules
            ruleType: param-flow
        ds4:
          apollo:
            namespaceName: application
            flowRulesKey: ${spring.application.name}-system-rules
            ruleType: system
        ds5:
          apollo:
            namespaceName: application
            flowRulesKey: ${spring.application.name}-auth-rules
            ruleType: authority

csp:
  sentinel:
    heartbeat:
      client:
        ip: '10.104.5.38'
    dashboard:
      server: 'http://10.104.9.91:8085'
    api:
      port: 8719

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 1000
#    # commandKey，默认为方法名
#    test:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"